### ISSUE TITLE
installation error (docker-compose pull)

### ISSUE THREAD

**Issue by bespiloy** [benjamin-maynard/Pi-Camera-in-a-box#6]
I need help on pulling the  pre-compiled images with the command of "docker-compose pull". See below for error messages I encountered:

pi@rpi3114:~/Pi-Camera-in-a-box $ docker-compose pull
Traceback (most recent call last):
  File "/home/pi/.local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/home/pi/.local/lib/python2.7/site-packages/compose/cli/main.py", line 18, in <module>
    import docker.errors
  File "/home/pi/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/pi/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/pi/.local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/home/pi/.local/lib/python2.7/site-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/home/pi/.local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/pi/.local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/pi/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/pi/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/pi/.local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/home/pi/.local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/home/pi/.local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname

Thanks.

**Comment by RickyMorgan** [comment]
Don't know if you were able to resolve this, but I ran into the same issue today (June 24, 2020) and found what appears to be the resolution by running the command sudo apt-get remove python-configparser as explained on the following web site: https://dev.to/vegasbrianc/comment/i0ka

Hope this helps.
Rick
